name: sync_code_to_GDrive
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  syncjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Upload a file to Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: <LOCAL_PATH_TO_YOUR_FILE>
          credentials: ${{ secrets.<YOUR_SERVICE_ACCOUNT_CREDENTIALS> }}
          parent_folder_id: <YOUR_DRIVE_FOLDER_ID>
